version: '3'
services:
  server:
    build: ./server
    ports:
      - "4000"
    working_dir: /
    volumes:
      - "./server/.env:/.env"
      - "./server/live.db:/live.db"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000"
    restart: unless-stopped
  nginx:
    build:
      context: ./.nginx
      args:
        DOMAIN: ohmy.codes,www.ohmy.codes
        EMAIL: gwanryo@gmail.com
    volumes:
      - "./.nginx/letsencrypt:/etc/letsencrypt"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
