version: '3'
services:
  server:
    build: server/
    ports:
      - "4000:4000"
    working_dir: /
    volumes:
      - "./server/.env:/.env"
      - "./server/live.db:/live.db"
  frontend:
    build: frontend/
    ports:
      - "3000"
  nginx:
    build:
      context: ./.nginx
    volumes:
      - /etc/nginx/vhost.d
      - /etc/acme.sh
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
