version: '3'
services:
  server:
    build: ./server
    ports:
      - "4000"
    working_dir: /
    volumes:
      - "./server/.env:/.env"
      - "./server/live.db:/live.db"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000"
    restart: unless-stopped
