version: '3'
services:
  server:
    build: server/
    ports:
      - "3000"
    working_dir: /
    volumes:
      - "./server/.env:/.env"
      - "./server/live.db:/live.db"
#  front:
#    build: front/
#    ports:
#      - "80:80"