version: '3'
services:
  server:
    image: gwanryo/ohmycodes-server
    ports:
      - "4000"
    working_dir: /
    volumes:
      - "./server/.env:/.env"
      - "./server/live.db:/live.db"
  frontend:
    image: gwanryo/ohmycodes-frontend
    ports:
      - "3000"
  nginx:
    build:
      context: ./.nginx
      args:
        DOMAIN: ohmy.codes,www.ohmy.codes
        EMAIL: gwanryo@gmail.com
    volumes:
      - "./.nginx/letsencrypt:/etc/letsencrypt"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
